### ISSUE TITLE
Loading external level files does not take world directory into account

### ISSUE THREAD

**Issue by edemartel** [Madour/LDtkLoader#13]
World files with external levels stores paths to those levels that are relative to the world file itself. However, the current level loader simply passes the path as is, which means that trying to load any world with external levels that is not in the current working for the process directory will fail.

**Comment by Madour** [comment]
Good catch, I didn't test enough I guess ^^' 

Replacing this line : 
https://github.com/Madour/LDtkLoader/blob/2e6749f646dfc9d34392d515bf93fb85fcc59acb/src/Level.cpp#L22

By

```c++
        std::ifstream in(w->getFilePath() + "/" + j["externalRelPath"].get<std::string>());
```
could probably fix the issue hopefully.

I'll try to fix this as soon as possible !
