### ISSUE TITLE
Texture coordinates are hardcoded to 16x16 tiles

### ISSUE THREAD

**Issue by edemartel** [Madour/LDtkLoader#14]
Using any other size tileset (for example, 32x32 tiles) will cause textures to be rendered incorrectly.

**Comment by Madour** [comment]
Thanks for reporting this issue, looks like the issue comes from this line :
https://github.com/Madour/LDtkLoader/blob/2e6749f646dfc9d34392d515bf93fb85fcc59acb/src/Layer.cpp#L189

hopefuly it should be easy to fix by replacing `16` by `cell_size`
