### ISSUE TITLE
Compile times, in particular external includes

### ISSUE THREAD

**Issue by s9w** [Madour/LDtkLoader#20]
Hey - cool library! I use it as a static library to keep the compile time of my main project small. Looking at the vcperf traces, it's still a bit of a sore spot in that regard. But I think it can be improved quite a bit:

An include of `World.hpp` takes ~800ms on my machine, 69% of which is `json.hpp` for example. That could be avoided with the use of its forward declarations for the necessary parameter I think. I'm sure there are other unnecessary includes but I didn't look into it in detail.

Thanks for writing this library.

**Comment by Madour** [comment]
Hi ! Thank you analyzing the build. I somewhat suspected my build times were too long.
I wasn't aware of this vcperf tool, it looks nice;

I tried analyzing the API_test target build, here is what I got for parsing:

![image](https://user-images.githubusercontent.com/11854124/167293323-c9f8f7ec-fda7-48ec-bdb4-1a6788533dfb.png)

Am I looking at the right analyzis ?

> use of its forward declarations for the necessary parameter

Yes you are right, this could also allow to move `json.hpp` to the src folder and avoid installing with the other headers probably.

**Comment by s9w** [comment]
What you're looking at is the etl output from the looks of it. It's more convenient to use the timetrace feature. So something like:

1. vcperf /start SessionName
2. compile
3. vcperf /stop SessionName /timetrace outputFile.json
4. In chrome, open chrome://tracing/ and drag the json into it.
5. Enable zoom mode (hotkey is "3") and zoom around with pressed mouse

And basically the json include is absolutely dominating the build time. I think that would be a pretty big win to move into the sources

**Comment by Madour** [comment]
Hey @s9w , I finally got time to work on this, please check MR #22 if you have some free time.
Thank you for reporting this issue, now projects that use this lib will have a significant decrease in compile time !

I'll wait a little bit before merging.

**Comment by s9w** [comment]
Cool, this worked just as well as expected!

Good enough for me. But if you want to go further, the next target would probably be the external optional. Did you use that to target C++11 (and not just C++17)? If so, you could include that only if `<optional>` is not available. Something like

```c++
#ifdef __cpp_lib_optional
#include <optional>
#else
#include "LDtkLoader/thirdparty/optional.hpp"
#endif
```

That uses the [C++20 feature test things](https://en.cppreference.com/w/cpp/feature_test), so it won't help for C++17. But many people are already on C++20 or C++23.

But that's just an idea. Thank you for that change!

**Comment by Madour** [comment]
You're welcome, #22 is merged.

Thank you for your suggestions, indeed it was for making the lib available for C++11 (even though I mostly use C++17 myself). 
I can see the benefit of including the standard optional when available, but even if we do, the `optional.hpp` file will still be present in the include folder because it is used in the template `Field<T>` struct.

So for now I think I'll keep it, even if getting rid of it would be nice.
