### ISSUE TITLE
Compile error: "Cannot use 'throw' with exceptions disabled"

### ISSUE THREAD

**Issue by dtori** [Madour/LDtkLoader#21]
First of all, thanks for sharing this lib :)

For my project I set -fno-exceptions to avoid the use of noexception keyword in all functions, 
I am getting this error when I try to compile LdtkLoader in my project.
to make it work I must eliminate all the throws in the optional.hpp file

Is there any possibility to remove the throws and replace them with something else without having to modify the original code?

Thanks!

**Comment by Madour** [comment]
Hello, you're wellcome, and thank you for using it !

Yes you can absolutely remove the usage of exceptions by giving the `-DLDTK_NO_THROW=True` option to cmake.

This will convert all throws to a error print and exit :)

**Comment by Madour** [comment]
Hello, thank you for using the lib and reporting this issue.

I suppose you already use the `-DLDTK_NO_THROW` option right ?
About the issue with optional.hpp, I didn't thought of this before tbh, so thank you for reporting it.

The easiest solution would be moving the lib to C++14 and use `std::optional`, would that fix your problem ? 

I was already considering moving to C++14 before to get rid of optional.hpp before, because I think most people use it now I believe.

**Comment by dtori** [comment]
Yes, I'm using -DLDTK_NO_THROW option.
I will try to use std::optional, since I am using C++17
Thanks for answering.

**Comment by Madour** [comment]
Hello @dtori, I see that you forked the project to fix this issue on your own. Do you plan to open a PR eventually? Or can I go ahead and try to fix this myself when I find time?

**Comment by dtori** [comment]
Hi Madour,

Go ahead and try to fix it yourself :)
My fix is just a hack to make it compile with emscripten and with clang (without exceptions). I still haven't been able to check that what I've done works correctly, it compiles, and I can generate a map without problems, but I haven't tried all the features of LDtkLoader yet.
The reason I forked is to use FetchContent in cmake for my project, but if you fix it, I'd rather use your repository in my cmake.

Thanks!

**Comment by Madour** [comment]
Okay, I'll work on this when I get some free time.

Btw, you can compile the lib with emscripten, by enabling exceptions catching 
. See https://github.com/Madour/LDtkViewer/blob/9dc4883588ba982d793c8ad857f3ffe307902f5e/CMakeLists.txt#L50, I even use FetchContent in that project.

**Comment by dtori** [comment]
Great! 
I didn't know -sNO_DISABLE_EXCEPTION_CATCHING. thanks for the tip.
I see that you have several repositories, when I have some time I will explore them, several seem interesting to me.
Thanks

**Comment by Madour** [comment]
This issue should now be fixed in commit bbb9058b558ad5b1d9bce1a947c0ea37abc0b090.

Selecting the LDTK_NO_THROW cmake option will now define the JSON_NOEXCEPT correctly!
