### ISSUE TITLE
Can't parse LDtk 1.2.0

### ISSUE THREAD

**Issue by jpvanoosten** [Madour/LDtkLoader#24]
It seems that LDtk 1.2.0 removed the `autoTilesetDefUid` property from the layer defs. This causes LDtkLoader to break when parsing 1.2.0 levels:
https://github.com/Madour/LDtkLoader/blob/6ee4be6c8520f98943c92507e6a5d1e42ee6ac7c/src/LayerDef.cpp#L21

nlohmann/json requires that these keys exist. An assertion is thrown if it doesn't exist:
https://github.com/Madour/LDtkLoader/blob/6ee4be6c8520f98943c92507e6a5d1e42ee6ac7c/src/json.hpp#L20306

**Comment by Madour** [comment]
Thank you for reporting and fixing this issue.
