### ISSUE TITLE
Update third party JSON.

### ISSUE THREAD

**Issue by reworks-org** [Madour/LDtkLoader#35]
nlohmann json recently got updated to 3.11.3, breaking compat with this library due to outdated included header.

Suggest either removing header or updating.

**Comment by Ryu204** [comment]
Hi, in my project I think the `json_fwd.hpp` is causing a problem with template definitions, but I am not sure how. I can provide the build log [here](https://godbolt.org/z/P1TMxxbdG).

I am using LdtkLoader version 1.5.2 and json latest's [master](https://github.com/nlohmann/json).

**Comment by Madour** [comment]
Thank you for the logs. Indeed, in the version 3.11.3, they introduced an additional template parameter for the json_base template, as you can see in this [commit](https://github.com/nlohmann/json/commit/bed648ca552258fa7b1d3065c2fa612877fa0918#diff-0b71bd06cd4c24d14f8788ca7a214c9aaddcaac5aec3c68fe907d888b7f6a2beR151).

They say it does not break compatibility, but it seems it did break in your case.

I'll update the version of the json lib in LDtkLoader, that should fix your issue.

**Comment by Madour** [comment]
I updated the json files to latest version: https://github.com/Madour/LDtkLoader/commit/f3a9f032804bc9f8b883ea56ff75da549547c55f

The latest [LDtkLoader 1.5.3](https://github.com/Madour/LDtkLoader/releases/tag/1.5.3) release should work well with your projects now.

**Comment by Ryu204** [comment]
Thank you very much!
