### ISSUE TITLE
How to parse intgrid and autotile layers?

### ISSUE THREAD

**Issue by SomeGuyDoinWork** [Madour/LDtkLoader#37]
Looking through examples and source code and theres not alot of documentation especially around autolayer and int grids.

Any chance of some documentation updates for it?

**Comment by Madour** [comment]
To get the int grid values, you can use the [`getIntGridValue`](https://github.com/Madour/LDtkLoader/wiki/Layer#getIntGridValue) method of a Layer. It will return an [IntGridValue ](https://github.com/Madour/LDtkLoader/wiki/DataTypes#struct--ldtkIntGridValue) that contains the value, name and color.

To get the tiles rendered in an Autolayer, you can use the [`allTiles`](https://github.com/Madour/LDtkLoader/wiki/Layer#allTiles) and [`getTile`](https://github.com/Madour/LDtkLoader/wiki/Layer#gettile) methods of a Layer. These methods return Tile instances that are created using the "autoLayerTiles" data from the ldtk file. You can look at the SFML or SDL examples, they both use `layer.allTiles()` to iterate on the tiles in an Autolayer to render the tiles.

This made me realize the wiki page for the ldtk::Tile class is missing. I will create it soon.

**Comment by SomeGuyDoinWork** [comment]
Thanks. But is there any way to get a list of tiles with their int grid id specifically? For example, if i wanted to mark those tiles as impassible, for creating collision boxes, or if i wanted to mark specific terrain types, etc. Maybe a key value pair of position, intgridvalue?

Something like: map<vec2, intgrid> ?

**Comment by Madour** [comment]
Okay, so if I understand correctly, you would like a way to get all tiles that have a specific intgrid value ?

An API like this:

```c++
auto Layer::getIntGridValuePositions(const string& name) -> vector<InPoint>;
auto Layer::getIntGridValuePositions(int intgrid_value) -> vector<InPoint>;
```

This could return all the position in grid coordinates of an IntGridValue occurrences.

For example, to get the positions of tiles that have the IntGridValue { 1, "collision", Color::Red} , you would do:

```c++
const auto& collision_tiles_pos = layer.getIntGridValuePositions("collision");

for (const auto& pos : collision_tiles_pos) {
    const auto& tile = layer.getTile(pos.x, pos.y);
    if (tile != ldtk::Tile::None) {
        // a tile exists, create a collision
    }
}
```

Is this what you are looking for ?

**Comment by SomeGuyDoinWork** [comment]
Yeah a way to get all tagged int grid tiles would be fantastic.

**Comment by Madour** [comment]
The APIs you requested were (finally) added !

Please check commit 8b6c344ef4c46475f382905513b4d19aff00eea9 for the IntGrid related APIs,
and commit eb24808c6d28aab3f9cb3cd5e0912f312c43ec53 for the EnumTag related APIs.

Basically, you can now do

```c++
// get all tiles in the layer that are tagged with the given enum value
const auto& collision_tiles = layer.getTilesByEnumTag(enum["collisions"]);

// get the positions of all the grass IntGridVal in the layer
const auto& grass_positions = layer.getIntGridValPositions("grass");

for (const auto& pos : grass_positions) {
  const auto& grass_tile = layer.getTile(pos.x, pos.y);
  // do something with grass tiles here
}
```
