### ISSUE TITLE
How do you read a field that is the Tile Type

### ISSUE THREAD

**Issue by JeffM2501** [Madour/LDtkLoader#45]
I have a custom field on an entity that is the type Tile (to tell me what texture to apply to a door). It doesn't look like I can read that data out of the entity, the field doesn't seem to be in the fields list.

Are tile fields like this read differently?

**Comment by JeffM2501** [comment]
Looking into the code I see that the tile field is just skipped. I am working around this by adding a new field type called TileRef that stores the tilesetId and the bounding rectangle provided, with this I can reverse lookup the tileID, but I would like to know if there is a correct way of doing this.
Thanks.

**Comment by Madour** [comment]
Hello, thank you for reporting this issue.

After checking, the Tile field is indeed not supported. For some reason, I did not know  it was possible to have Tile fields.
Sorry for the inconvenience, I will try to fix this soon.

After looking again at the test file in LDtk repository, Tile fields are not used in it, so that could explain why I missed them.

**Comment by JeffM2501** [comment]
This is what I did to implement it here, in case it helps your implementation https://github.com/JeffM2501/ModernBoomerShooter/blob/8dee70fd32e546d9316aec8ddb64079a0a0ff5ec/game/src/external/LDtkLoader/src/FieldsContainer.cpp#L179

I added a TileRef struct, and read in the data from the tile field. It's working very well for me, I can backplot the tile sheet id and rectangle to the tile ID that I need.

**Comment by JeffM2501** [comment]
This is my use case for reference. I have a door entity that takes a tile as a field.
![image](https://github.com/user-attachments/assets/ec568b76-6a29-46aa-8e2a-b9308648b343)
Then in game I use that object to create the door entity with that tile as it's texture.
![image](https://github.com/user-attachments/assets/f628087f-f2d8-4844-b0ee-5e7114849461)

**Comment by Madour** [comment]
Hello, 

For your use case, I believe you could have used the "Editor visual" property of the entity in the editor.

Anyways, I added support for Tile fields in 28956363856c9580bb6198a338fe54dee6685c36

Please let me know if it works for you.

**Comment by JeffM2501** [comment]
Thank you very much, I'll try it out.

This was a simple use case, I have other cases where I need more than one texture for some entities so the single editor visual would not be sufficient, so this will be perfect.
