### ISSUE TITLE
No Way to Get List of All Entities

### ISSUE THREAD

**Issue by dontpanic5** [Madour/LDtkLoader#6]
I see that there are calls to get entities by id/name in a layer and also the entity defs can be gotten by id/name.
But it seems like I would need to already know all the entities I need beforehand.
So if I get a ldtk file without prior knowledge of the entities it can have, there's no way to know what id/names to call.

**Comment by Madour** [comment]
Indeed, initially when I designed the thing, I supposed that the user created the levels and knows the name of their entities.

However, I can see why one would want a way to iterate over all the entities regardless of the name, or even on all the defs.
